### ISSUE TITLE
Emacs freezes after popweb-latex-mode 

### ISSUE THREAD

**Issue by niwaka-ame** [manateelazycat/popweb#24] opened 2022-01-04 11:58 UTC
Problem: After `M-x popweb-latex-mode` in org-mode, Emacs freezes and CPU is 100% occupied by Python and Emacs, and the whole OS was very slow. 

The same problem was reproducible with `emacs -Q` (loaded with exactly the same config as instructed in readme) and I couldn't do anything on Emacs except killing the process from terminal. 

`popweb-dict-bing` seemed to work fine, so I suspected it's an issue specific to `popweb-latex`, but I couldn't get the content of `*popweb*` buffer because Emacs was frozen. 

More info:
Manjaro i3: 21.1
Python: 3.9.9
Emacs: 27.2
epc: 0.0.5
python-pyqt5: 5.15.6-2

**Comment by MatthewZMD** [comment] 2022-01-05 00:09
I'm on Manjaro KDE and cannot reproduce your freezing. Have you tried to inspect the `strace` results?

**Comment by manateelazycat** [comment] 2022-01-21 12:52
@niwaka-ame can you try newest version?

**Comment by MatthewZMD** [comment] 2022-01-21 19:01
This is likely to be fixed in the latest version

**Comment by MatthewZMD** [comment] 2022-01-22 20:23
Please re-open if the problem still persists.

**Closed as completed by MatthewZMD** 2022-01-22 20:23 UTC
Labels: help wanted

**Comment by niwaka-ame** [comment] 2022-02-22 10:17
Thank you. I'll test it. Sorry - I just noticed this.
